controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_page:
    path: /
    controller: App\Controller\PageController::index



