<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBSuoVr1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBSuoVr1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBSuoVr1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBSuoVr1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBSuoVr1\App_KernelDevDebugContainer([
    'container.build_hash' => 'BSuoVr1',
    'container.build_id' => 'c9501915',
    'container.build_time' => 1697894959,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBSuoVr1');
