<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBuRpUmi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBuRpUmi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBuRpUmi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBuRpUmi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBuRpUmi\App_KernelDevDebugContainer([
    'container.build_hash' => 'BuRpUmi',
    'container.build_id' => 'e5aff9b4',
    'container.build_time' => 1697201952,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBuRpUmi');
